name: Release ISO
description: 'Builds an ISO bundled with the provided Kickstart configuration'

inputs:
  image-name:
    description: 'Name of the image to build'
    required: true
  installer-major-version:
    description: 'Major version of the installer to use'
    required: true
  installer-repo:
    description: 'Fedora repository to use for the installer'
    required: false
    default: 'releases'
  kickstart-file-path:
    description: 'Path to the kickstart file'
    required: true
  cpu-arch:
    description: 'CPU architecture for installer'
    required: false
    default: x86_64
  output-filename:
    description: 'Output ISO filename'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Calculate ISO name
      id: iso-name
      shell: bash
      run: |
        if [[ -z "${{inputs.output-filename }}" ]]; then
          ISO_NAME="${{ inputs.image-name }}-${{ inputs.installer-major-version }}-${{ inputs.cpu-arch }}-$(date +%Y%m%d).iso"
        else
          ISO_NAME="${{ inputs.output-filename }}"
        fi
          echo "ISO name: ${ISO_NAME}"
          echo "iso_name=${ISO_NAME}" >> $GITHUB_OUTPUT

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        PACKAGES=$(cat deps.txt)
        dnf install \
          --disablerepo='*' \
          --enablerepo='fedora,updates' \
          --setopt install_weak_deps=0 \
          --assumeyes \
          $PACKAGES
        
    - name: Download Fedora Everything Installer
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        curl -L $EVERYTHING_INSTALLER_URL -o Fedora-Everything-netinst-${{ inputs.cpu-arch }}.iso
      env:
        EVERYTHING_INSTALLER_URL: https://mirror.fcix.net/fedora/linux/${{ inputs.installer-repo }}/${{ inputs.installer-major-version }}/Everything/${{ inputs.cpu-arch }}/os/images/boot.iso
        
    - name: Build ISO
      shell: bash
      id: build
      working-directory: ${{ github.action_path }}
      run: |
        ./isopatch.sh Fedora-Everything-netinst-${{ inputs.cpu-arch }}.iso ${{ steps.iso-name.outputs.iso_name }}
        echo "ISO_FILENAME=${{ steps.iso-name.outputs.iso_name }}" >> $GITHUB_OUTPUT
        
    - name: Calculate SHA256 
      id: calculate
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "# ${{ steps.iso-name.outputs.iso_name }}: $(stat -c '%s' ${{ steps.iso-name.outputs.iso_name }}) bytes" > ${{ github.workspace }}/${{ steps.iso-name.outputs.iso_name }}.sha256sum
        sha256sum --tag "${{ steps.iso-name.outputs.iso_name }}" >> ${{ github.workspace }}/${{ steps.iso-name.outputs.iso_name }}.sha256sum
        cat ${{ steps.iso-name.outputs.iso_name }}.sha256sum
        echo "SHA256SUM_FILENAME=${{ steps.iso-name.outputs.iso_name }}.sha256sum" >> $GITHUB_OUTPUT

outputs:
  sha256sum-path:
    description: 'Path to the calculated sha256sum'
    value: ${{ steps.calculate.outputs.SHA256SUM_FILENAME }}
  iso-path:
    description: 'Path to the generated ISO'
    value: ${{ steps.build.outputs.ISO_FILENAME }}
  iso-name:
    description: 'ISO name without path'
    value: ${{ steps.iso-name.outputs.iso_name }}
