name: Release ISO
description: 'Builds an ISO bundled with the provided Kickstart configuration'

inputs:
  image-name:
    description: 'Name of the image to build'
    required: true
  installer-major-version:
    description: 'Major version of the installer to use'
    required: true
  installer-repo:
    description: 'Fedora repository to use for the installer'
    required: false
    default: 'releases'
  kickstart-file-path:
    description: 'Path to the kickstart file'
    required: true

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        dnf install -y lorax curl 

    - name: Download Fedora Everything Installer
      shell: bash
      run: |
        curl -L $EVERYTHING_INSTALLER_URL -o Fedora-Everything-netinst-x86_64.iso
      env:
        EVERYTHING_INSTALLER_URL: https://mirror.fcix.net/fedora/linux/${{ inputs.installer-repo }}/${{ inputs.installer-major-version }}/Everything/x86_64/os/images/boot.iso

    - name: Build ISO
      shell: bash
      id: build
      run: |
        mkksiso --ks ${{ inputs.kickstart-file-path }} Fedora-Everything-netinst-x86_64.iso ${{ inputs.image-name }}.iso
        echo "ISO_FILENAME=${{ inputs.image-name }}.iso" >> $GITHUB_OUTPUT

sha256:
  name: sha256
  runs-on: ubuntu-latest
  steps:
    - name: ISO url
      run: ${{ inputs.image-name }}.iso
    - name: Calculate SHA256 
      run: |
        sha256sum ${{ inputs.image-name }}.iso | awk '{print $1}' > ${{ inputs.image-name }}.sha256sum
        echo "SHA256SUM_FILENAME=${{ inputs.image-name }}.sha256sum" >> $GITHUB_OUTPUT

outputs:
  sha256sum-path:
    description: 'Path to the calculated sha256sum'
    value: ${{ steps.build.outputs.SHA256SUM_FILENAME }}
  iso-path:
    description: 'Path to the generated ISO'
    value: ${{ steps.build.outputs.ISO_FILENAME }}
