#!/bin/bash

get_esp_offset() {

    IMG_FILE="$1"
    parted --json --script "${IMG_FILE}" \
        unit b \
        print list \
        | jq --raw-output '
            .disk.partitions[]
            | select(.number == 2)
            '
}

get_esp_offset "$1"
